In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Car_Price_Cleaned.csv')

In [3]:
df.info

<bound method DataFrame.info of      car_ID  symboling                  CarName    CarModel_Standardised  \
0         1          3        alfa romeo giulia        alfa romeo giulia
1         2          3       alfa romeo stelvio       alfa romeo stelvio
2         3          1  alfa romeo Quadrifoglio  alfa romeo quadrifoglio
3         4          2              audi 100 ls                 audi 100
4         5          2              audi 100 ls                 audi 100
..      ...        ...                      ...                      ...
200     201         -1          volvo 145e (sw)          volvo 145e (sw)
201     202         -1              volvo 144ea         volvo 140 series
202     203         -1              volvo 244dl         volvo 240 series
203     204         -1                volvo 246         volvo 240 series
204     205         -1              volvo 264gl         volvo 260 series

    fueltype aspiration  doornumber      carbody drivewheel enginelocation  \
0        gas        std           2  convertible        rwd          front
1        gas        std           2  convertible        rwd          front
2        gas        std           2    hatchback        rwd          front
3        gas        std           4        sedan        fwd          front
4        gas        std           4        sedan        4wd          front
..       ...        ...         ...          ...        ...            ...
200      gas        std           4        sedan        rwd          front
201      gas      turbo           4        sedan        rwd          front
202      gas        std           4        sedan        rwd          front
203   diesel      turbo           4        sedan        rwd          front
204      gas      turbo           4        sedan        rwd          front

     ...  fuelsystem  boreratio  stroke  compressionratio  horsepower peakrpm  \
0    ...        mpfi       3.47    2.68               9.0         111    5000
1    ...        mpfi       3.47    2.68               9.0         111    5000
2    ...        mpfi       2.68    3.47               9.0         154    5000
3    ...        mpfi       3.19    3.40              10.0         102    5500
4    ...        mpfi       3.19    3.40               8.0         115    5500
..   ...         ...        ...     ...               ...         ...     ...
200  ...        mpfi       3.78    3.15               9.5         114    5400
201  ...        mpfi       3.78    3.15               8.7         160    5300
202  ...        mpfi       3.58    2.87               8.8         134    5500
203  ...         idi       3.01    3.40              23.0         106    4800
204  ...        mpfi       3.78    3.15               9.5         114    5400

     citympg  highwaympg    price  manufacturer
0         21          27  13495.0    alfa romeo
1         21          27  16500.0    alfa romeo
2         19          26  16500.0    alfa romeo
3         24          30  13950.0          audi
4         18          22  17450.0          audi
..       ...         ...      ...           ...
200       23          28  16845.0         volvo
201       19          25  19045.0         volvo
202       18          23  21485.0         volvo
203       26          27  22470.0         volvo
204       19          25  22625.0         volvo

[205 rows x 28 columns]>

In [4]:
df.head(10)

,car_ID,symboling,CarName,CarModel_Standardised,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,...,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,manufacturer
0,1,3,alfa romeo giulia,alfa romeo giulia,gas,std,2,convertible,rwd,front,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.000,alfa romeo
1,2,3,alfa romeo stelvio,alfa romeo stelvio,gas,std,2,convertible,rwd,front,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.000,alfa romeo
2,3,1,alfa romeo Quadrifoglio,alfa romeo quadrifoglio,gas,std,2,hatchback,rwd,front,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.000,alfa romeo
3,4,2,audi 100 ls,audi 100,gas,std,4,sedan,fwd,front,...,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.000,audi
4,5,2,audi 100 ls,audi 100,gas,std,4,sedan,4wd,front,...,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.000,audi
5,6,2,audi fox,audi fox,gas,std,2,sedan,fwd,front,...,mpfi,3.19,3.40,8.5,110,5500,19,25,15250.000,audi
6,7,1,audi 100 ls,audi 100,gas,std,4,sedan,fwd,front,...,mpfi,3.19,3.40,8.5,110,5500,19,25,17710.000,audi
7,8,1,audi 5000,audi 5000,gas,std,4,wagon,fwd,front,...,mpfi,3.19,3.40,8.5,110,5500,19,25,18920.000,audi
8,9,1,audi 4000,audi 4000,gas,turbo,4,sedan,fwd,front,...,mpfi,3.13,3.40,8.3,140,5500,17,20,23875.000,audi
9,10,0,audi 5000s (diesel),audi 5000s (diesel),gas,turbo,2,hatchback,4wd,front,...,mpfi,3.13,3.40,7.0,160,5500,16,22,17859.167,audi

In [5]:
df.describe()

,car_ID,symboling,doornumber,wheelbase,carlength,carwidth,carheight,curbweight,cylindernumber,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,103.000000,0.834146,3.121951,98.756585,174.049268,65.907805,53.724878,2555.565854,4.380488,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,59.322565,1.245307,0.994966,6.021776,12.337289,2.145204,2.443522,520.680204,1.080854,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,1.000000,-2.000000,2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,2.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,52.000000,0.000000,2.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,4.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,103.000000,1.000000,4.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,4.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,154.000000,2.000000,4.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,4.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,205.000000,3.000000,4.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,12.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000